import os
import json
import base64
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import requests
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="Floorplan Processor API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

NVIDIA_API_KEY = os.getenv("NVIDIA_API_KEY")
# Or specify the exact NIM model URL if using a specific model.
# e.g., "https://ai.api.nvidia.com/v1/chat/completions" for vision models (like NVDIA's Llama 3.2 90B Vision or similar)
NVIDIA_API_URL = "https://ai.api.nvidia.com/v1/chat/completions"

@app.post("/api/v1/process-floorplan")
async def process_floorplan(file: UploadFile = File(...)):
    """
    Receives an architectural floor plan image (PNG/JPG/PDF),
    sends it to NVIDIA vision model, and returns extracted JSON data.
    """
    if not NVIDIA_API_KEY:
        raise HTTPException(status_code=500, detail="NVIDIA API Key is missing in .env file.")

    allowed_types = ["image/jpeg", "image/png", "application/pdf"]
    if file.content_type not in allowed_types:
        raise HTTPException(status_code=400, detail=f"Unsupported file type: {file.content_type}")
    
    try:
        contents = await file.read()
        
        # If it's a PDF, ideally we would convert to image first, but for this example, 
        # we'll assume the vision model supports it or we send the base64 payload.
        # Let's base64 encode the content
        encoded_image = base64.b64encode(contents).decode("utf-8")
        
        # Prepare the payload for NVIDIA API (assuming a vision model like Llama 3.2 Vision)
        headers = {
            "Authorization": f"Bearer {NVIDIA_API_KEY}",
            "Accept": "application/json"
        }
        
        # Prompt instructing the model to extract room boundaries, walls, doors, etc. in JSON
        prompt = """
        You are an expert architectural assistant. Analyze the provided floor plan image.
        Extract the architectural structure including:
        1. Walls (start and end coordinates, or length)
        2. Rooms (names, boundaries, width/height)
        3. Doors and Windows (locations)
        4. Manual measurement labels if any.
        
        Return ONLY a valid JSON object matching this schema:
        {
          "rooms": [
            { "id": "room_1", "name": "Living Room", "x": 0, "y": 0, "width": 300, "height": 400, "color": "#e2e8f0" }
          ],
          "walls": [],
          "doors": [],
          "windows": []
        }
        """
        
        # Note: Depending on the specific NVIDIA NIM model, the payload structure might differ slightly.
        # This uses the OpenAI-compatible chat completions structure for vision.
        payload = {
            "model": "meta/llama-3.2-90b-vision-instruct", # Example model, change as needed
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": prompt
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:{file.content_type};base64,{encoded_image}"
                            }
                        }
                    ]
                }
            ],
            "max_tokens": 1024,
            "temperature": 0.1,
            "response_format": {"type": "json_object"}
        }

        response = requests.post(NVIDIA_API_URL, headers=headers, json=payload, timeout=60)
        
        if response.status_code != 200:
            error_details = response.text
            print(f"NVIDIA API Error: {error_details}")
            raise HTTPException(status_code=response.status_code, detail="Error communicating with NVIDIA API.")
        
        response_data = response.json()
        
        # Extract the JSON response generated by the model
        model_content = response_data['choices'][0]['message']['content']
        
        try:
            extracted_json = json.loads(model_content)
            return extracted_json
        except json.JSONDecodeError:
            print(f"Failed to parse JSON from model output: {model_content}")
            raise HTTPException(status_code=500, detail="Failed to parse model output as JSON.")
            
    except Exception as e:
        print(f"Exception during processing: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))
